# --------------------------------------------------------------------------------------------------

- name: ..... retrieve node info

  uri:
    url: "https://{{ nodes[0].nodeip }}/api/cluster/nodes?fields=*&return_records=true&return_timeout=15"
    method: GET
    headers:
      Content-Type: "application/json"
    user: "{{ username }}"
    password: "{{ password }}"
    status_code: 200
    validate_certs: False

  register: nodeinfo_response

# --------------------------------------------------------------------------------------------------

- name: ..... retrieve node 1 cluster interface address

  set_fact:
    ciplist: "{{ ciplist | default([]) + [ {'nodeip': nodes[0].nodeip, 'cip': nodeinfo_response.json.records[1].cluster_interfaces[0].ip.address} ] }}"

- name: ..... retrieve node 2 cluster interface address

  set_fact:
    ciplist: "{{ ciplist + [ {'nodeip': nodes[1].nodeip, 'cip': nodeinfo_response.json.records[0].cluster_interfaces[0].ip.address} ] }}"
  
# --------------------------------------------------------------------------------------------------
